version: 3.8

services: 
    configurationserver:
        build: ./eurekaserver
        ports: 
            - "6000:6000"
        network:
            - final-project
        depends_on:
            - configurationserver 

    eureka:
        build: ./eurekaserver
        ports: 
            - "8761:8761"
        network:
            - final-project
        depends_on:
            - configurationserver 

    zuul:
        build: ./zuul
        ports: 
            - "8080:8080"
        network:
            - final-project
        depends_on:
            - eureka    
        

volumes:
    db-data
            
networks:
    final-project:
        driver: bridge 