/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notificationmicro;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@EnableDiscoveryClient
@EnableCircuitBreaker
@SpringBootApplication
public class NotificationMicro {
    public static void main(String[] args) {
        SpringApplication.run(NotificationMicro.class, args);
    }
}
